In [1]:
import numpy as np
a=np.random.randint(1,100)
a


40

In [2]:
m=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
top=0
bottom=len(m[0])-1

left=0
right=len(m)-1

while(top<bottom and left<right):
        
    prev=m[top+1][left]
    for i in range(left,right+1):
        current=m[top][i]
        m[top][i]=prev
        prev=current
    top+=1
    
    for j in range(top,bottom+1):
        current=m[j][right]
        m[j][right]=prev
        prev=current
    right-=1    
    
    for i in range(right,left-1,-1):
        current=m[bottom][i]
        m[bottom][i]=prev
        prev=current
    bottom-=1
    
    for i in range(bottom,top-1,-1):
        current=m[i][left]
        m[i][left]=prev
        prev=current
    left+=1    
print(m)    

[[4, 1, 2], [7, 5, 3], [8, 9, 6]]


In [3]:
m=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
a=[[m[i][j] for i in range(len(m))]for j in range(len(m[0]))]
for t in a:
    print(t)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [4]:
m=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
# a=[[0,0,0],
#    [0,0,0],
#    [0,0,0]
#   ]

a=np.zeros([3,3])
for i in range(len(m)):
    for j in range(len(m[0])):
        a[j][i]=m[i][j]
for k in a:
    print(k)

[1. 4. 7.]
[2. 5. 8.]
[3. 6. 9.]


In [5]:
import numpy as np
a=np.zeros([3,3])
a



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
mat=[[1,2,3],
     [4,5,6],
     [7,8,9],
    ] 
top=0
bottom=len(mat)-1

left=0
right=len(mat[0])-1

while(top<bottom and left<right):
    
    prev=mat[top+1][left]
    
    for i in range(left,right+1):
        current=mat[top][i]
        mat[top][i]=prev
        prev=current
    top+=1 
    


    for i in range(top,bottom+1):
        current=mat[i][right]
        mat[i][right]=prev
        prev=current
    right-=1
    
    for i in range(right,left-1,-1):
        current=mat[bottom][i]
        mat[bottom][i]=prev
        prev=current
    bottom-=1   
    
    for i in range(bottom,top-1,-1):
        current=mat[i][left]
        mat[i][left]=prev
        prev=current
    left+=1    
print(mat)

[[4, 1, 2], [7, 5, 3], [8, 9, 6]]


In [7]:
a=[5,9,8]
b=[4,3,2]
c=[7,1,4]
ma=np.matrix([a,b,c])


In [8]:
# Transpose of matrix using T

ma.T

matrix([[5, 4, 7],
        [9, 3, 1],
        [8, 2, 4]])

In [9]:
# Transpose of matrix Using transpose()

ma.transpose()

matrix([[5, 4, 7],
        [9, 3, 1],
        [8, 2, 4]])

In [10]:
# Inverse of matrix
ma.I

matrix([[-0.09615385,  0.26923077,  0.05769231],
        [ 0.01923077,  0.34615385, -0.21153846],
        [ 0.16346154, -0.55769231,  0.20192308]])

In [11]:
# x + y − z = 4

# x − 2y + 3z = −6

# 2x + 3y + z = 7

In [12]:
left_side=np.matrix([[1,1,-1],
           [1,-2,3],
           [2,3,1]])
left_side


matrix([[ 1,  1, -1],
        [ 1, -2,  3],
        [ 2,  3,  1]])

In [13]:
right_side=np.matrix([[4],
                      [-6],
                      [7]])

In [14]:
#solution:
left_side_inverse=left_side.I
left_side_inverse

matrix([[ 0.84615385,  0.30769231, -0.07692308],
        [-0.38461538, -0.23076923,  0.30769231],
        [-0.53846154,  0.07692308,  0.23076923]])

In [15]:
solution=left_side_inverse*right_side
solution

matrix([[ 1.],
        [ 2.],
        [-1.]])

In [16]:
#for check your result:



In [17]:
a=np.array(np.arange(24).reshape(2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
b=np.append(a,[23,24,25,26])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 23, 24, 25, 26])

In [19]:
t=np.array(np.random.randint(1,100,20).reshape(2,2,5))
t

array([[[25, 24, 29, 95, 51],
        [59, 32, 84, 75, 89]],

       [[81, 67, 93, 39, 90],
        [58, 57, 93, 79, 71]]])

In [20]:
t1=np.array(np.arange(20).reshape(2,2,5))*10+3
t1

array([[[  3,  13,  23,  33,  43],
        [ 53,  63,  73,  83,  93]],

       [[103, 113, 123, 133, 143],
        [153, 163, 173, 183, 193]]])

In [21]:
#append using axis

np.append(t,t1,axis=0)

array([[[ 25,  24,  29,  95,  51],
        [ 59,  32,  84,  75,  89]],

       [[ 81,  67,  93,  39,  90],
        [ 58,  57,  93,  79,  71]],

       [[  3,  13,  23,  33,  43],
        [ 53,  63,  73,  83,  93]],

       [[103, 113, 123, 133, 143],
        [153, 163, 173, 183, 193]]])

In [22]:
np.append(t,t1,axis=1)

array([[[ 25,  24,  29,  95,  51],
        [ 59,  32,  84,  75,  89],
        [  3,  13,  23,  33,  43],
        [ 53,  63,  73,  83,  93]],

       [[ 81,  67,  93,  39,  90],
        [ 58,  57,  93,  79,  71],
        [103, 113, 123, 133, 143],
        [153, 163, 173, 183, 193]]])

In [23]:
np.append(t,t1,axis=2)

array([[[ 25,  24,  29,  95,  51,   3,  13,  23,  33,  43],
        [ 59,  32,  84,  75,  89,  53,  63,  73,  83,  93]],

       [[ 81,  67,  93,  39,  90, 103, 113, 123, 133, 143],
        [ 58,  57,  93,  79,  71, 153, 163, 173, 183, 193]]])

In [24]:
l=[5,3,6,2,4]
l.extend([9,78,89])

len(l)

8

In [25]:
l.append([10,20,30])

In [26]:
print(len(l))
l

9


[5, 3, 6, 2, 4, 9, 78, 89, [10, 20, 30]]

In [27]:
import copy
c=copy.copy(l)
c[8][0]=3
c

[5, 3, 6, 2, 4, 9, 78, 89, [3, 20, 30]]

In [28]:
l

[5, 3, 6, 2, 4, 9, 78, 89, [3, 20, 30]]

In [29]:
d=copy.deepcopy(l)
d[8][1]=7
d

[5, 3, 6, 2, 4, 9, 78, 89, [3, 7, 30]]

In [30]:
l

[5, 3, 6, 2, 4, 9, 78, 89, [3, 20, 30]]