In [1]:
import numpy as np

In [4]:
d=np.array([1,2,3,4,5])

In [6]:
print(d)
print(type(d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import array as array

In [12]:
l=array.array('i',[1,2,3,4,5,6])

In [13]:
print(l)

array('i', [1, 2, 3, 4, 5, 6])


In [14]:
print(type(l))

<class 'array.array'>


In [15]:
np.array((1,2,3))

array([1, 2, 3])

In [30]:
a=np.array([[-1, 2, 0, 4],
          [4, -0.5, 6, 0],
          [2.6, 0, 7, 8],
          [3, -7, 4, 2.0]])
print(a[:2,::2])

[[-1.  0.]
 [ 4.  6.]]


In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
a.shape

(4, 4)

In [48]:
type(a)

numpy.ndarray

In [49]:
a.dtype

dtype('float64')

In [51]:
a.ndim

2

In [52]:
a.size

16

In [53]:
a.T

array([[-1. ,  4. ,  2.6,  3. ],
       [ 2. , -0.5,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])

In [60]:
np.arange(10,2)

array([], dtype=int64)

In [62]:
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [98]:
a[0:4,1]

array([ 2. , -0.5,  0. , -7. ])

In [100]:
a.shape

(4, 4)

In [103]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,12,14])
r=arr.reshape(4,3)
r


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 14]])

In [105]:
# 2d
s=arr.reshape(2,3,2)
s

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [12, 14]]])

In [108]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [109]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [110]:
#Numpy jion array

In [129]:
#1d array
a1=np.array([7,8,9])
a2=np.array([6,4,3])
fa=np.concatenate((a1,a2))
fa=np.concatenate((a2,a1))
fa

array([6, 4, 3, 7, 8, 9])

In [132]:
# vstack
s=np.vstack((a1,a2))
s

array([[7, 8, 9],
       [6, 4, 3]])

In [134]:
#hstack
h=np.hstack((a1,a2))
h

array([7, 8, 9, 6, 4, 3])

In [137]:
#dstack
d=np.dstack((a1,a2))
d

array([[[7, 6],
        [8, 4],
        [9, 3]]])

In [139]:
#2d Array
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
f=np.concatenate((a1,a2))
print(f)
f=np.concatenate((a1,a2),axis=0)
print(f)
f=np.concatenate((a1,a2),axis=1)
print(f)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [140]:
#vstack
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [141]:
#hstack
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [142]:
# dstack
np.dstack((a1,a2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [ ]:
# Numpy split

In [143]:
#array_split

In [147]:
s=np.array([1,2,3,4,5,6,7,8,9])
np.array_split(s,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
# arange
#arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. 
#The interval mentioned is half opened i.e. [Start, Stop)

In [150]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [152]:
#linspace
#numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None) : Returns number spaces evenly 
#w.r.t interval. Similar to arange but instead of step it uses sample number.

In [154]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
#random

In [158]:
np.random.rand(10)

array([0.57617356, 0.20584578, 0.48939251, 0.9058142 , 0.73961291,
       0.46686879, 0.49738519, 0.6493164 , 0.61858055, 0.97588263])

In [159]:
np.random.randn(10)

array([ 1.04558563, -0.32613308, -0.73897146,  0.23582528,  0.04830147,
        0.78769125, -1.21918872, -0.83218351,  0.55068744,  0.51966673])

In [163]:
np.random.randint(1,100,90)

array([36, 76,  8, 14, 72, 33, 28, 10, 86, 69,  9, 34, 98, 40, 54,  5, 86,
       37,  2, 61, 19,  9, 98, 10, 18, 64, 65, 53,  1, 59, 73, 31, 41, 30,
       46, 68, 35, 92, 75, 75, 50, 96, 12, 48, 90,  4, 70, 83, 43, 85, 93,
       99, 80, 69, 94, 39,  6, 93, 21, 99, 79, 92, 75, 97, 48, 80, 79, 76,
       24, 40, 47, 43, 84, 87,  9, 89, 70, 36, 20, 65, 89, 21, 71, 67, 36,
       75, 53,  2, 53, 92])